name = "artemis-beauty-salon"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "APPOINTMENTS_KV"
id = "a32bdb6085764031a859d07eae6e7829"

[[kv_namespaces]]
binding = "SUBSCRIBERS_KV"
id = "4abdba7b441041b19e57400ab2da492c"
